name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - uses: actions/checkout@v4

    # Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers to speed up builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Log in to AWS ECR
    - name: Log in to AWS ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Tag Docker image for Docker Hub
    - name: Tag Docker image for Docker Hub
      run: |
        docker tag 968721aed6bf sainathmandala90/pharmetrade:latest

    # Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push sainathmandala90/pharmetrade:latest

    # Tag Docker image for AWS ECR
    - name: Tag Docker image for AWS ECR
      run: |
        docker tag 968721aed6bf 311141530448.dkr.ecr.us-east-1.amazonaws.com/pharmetrade:latest

    # Push Docker image to AWS ECR
    - name: Push Docker image to AWS ECR
      run: |
        docker push 311141530448.dkr.ecr.us-east-1.amazonaws.com/pharmetrade:latest
