name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # make sure this matches your ECR region

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker image to ECR
        run: |
          IMAGE_NAME="490457333469.dkr.ecr.us-east-1.amazonaws.com/jaisai_afroz"
          TAG="latest"
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG

      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 and redeploy Docker container
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            IMAGE="490457333469.dkr.ecr.us-east-1.amazonaws.com/jaisai_afroz"
            CONTAINER="serverupc-container"

            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 925623962804.dkr.ecr.ap-south-2.amazonaws.com

            docker ps -a --format '{{.Names}}' | grep -w $CONTAINER && docker rm -f $CONTAINER || true
            docker pull $IMAGE
            docker run -d -p 3000:3000 --name $CONTAINER $IMAGE
          EOF
